name: Enviar Palabra del Día

on:
  schedule:
    - cron: '0 7 * * *'  # Ejecutar todos los días a las 15:00 UTC (12:00 Argentina)
  workflow_dispatch:

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - name: Notificar devocional diario
        run: |
          curl -X POST https://fundacionmisionvida7.vercel.app/api/send-notification \
            -H "Content-Type: application/json" \
            -d '{
              "title": "📖 Palabra del Día",
              "body":  "¡Tu devocional de hoy ya está disponible!"
            }'

# Cambio menor para forzar redeploy
# Comentario para forzar redeploy desde el móvil
