name: Enviar Palabra del Día

on:
  schedule:
    - cron: '0 7 * * *'  # Todos los días a las 7:00 UTC → 4:00 Argentina
  workflow_dispatch:      # Permite ejecución manual

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - name: Verificar estado del servicio
        run: |
          echo "🔍 Verificando estado del backend antes de enviar..."
          HEALTH_CHECK=$(curl -s -o /dev/null -w "%{http_code}" \
            "https://nuevo-palabra-del-dia-backend.vercel.app/api/send-notification?type=daily" \
            --connect-timeout 10)
          
          echo "📊 Status del health check: $HEALTH_CHECK"
          
          if [ "$HEALTH_CHECK" -eq 200 ]; then
            echo "✅ Servicio respondiendo correctamente"
          else
            echo "⚠️ Servicio puede estar en cold start"
          fi

      - name: Warm-up del backend
        run: |
          echo "🔥 Calentando backend para evitar cold start..."
          curl -s "https://nuevo-palabra-del-dia-backend.vercel.app/api/send-notification?type=daily" \
            --connect-timeout 30 \
            --max-time 45 > /dev/null 2>&1 &
          
          echo "⏳ Esperando 20 segundos para cold start..."
          sleep 20

      - name: Enviar notificación diaria
        run: |
          echo "🔔 Enviando notificación diaria..."
          
          RESPONSE=$(curl -s -w "\n%{http_code}" -X GET \
            "https://nuevo-palabra-del-dia-backend.vercel.app/api/send-notification?type=daily" \
            -H "Content-Type: application/json" \
            -H "User-Agent: GitHub-Actions-Daily/1.0" \
            --connect-timeout 60 \
            --max-time 120)
          
          HTTP_CODE=$(echo "$RESPONSE" | tail -n1)
          RESPONSE_BODY=$(echo "$RESPONSE" | head -n -1)
          
          echo "📡 Código HTTP: $HTTP_CODE"
          echo "📦 Respuesta completa: $RESPONSE_BODY"
          
          if [ "$HTTP_CODE" -eq 200 ]; then
            echo "✅ NOTIFICACIÓN ENVIADA EXITOSAMENTE"
            echo "📖 Los usuarios recibirán: Palabra del Día"
            echo "🎯 Topic: daily"
            echo "🕐 Timestamp: $(date -u)"
          else
            echo "❌ ERROR: Código HTTP $HTTP_CODE"
            echo "💥 Respuesta del servidor: $RESPONSE_BODY"
            exit 1
          fi
        timeout-minutes: 5
