name: Enviar Palabra del Día

on:
  schedule:
    - cron: '0 7 * * *'  # Todos los días a las 7:00 UTC → 4:00 Argentina
  workflow_dispatch:

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - name: Enviar notificación diaria
        run: |
          curl -v "https://nuevo-palabra-del-dia-backend.vercel.app/api/send-notification?type=daily" \
            -H "Content-Type: application/json" \
            -H "User-Agent: Mozilla/5.0 (GitHub Actions)" \
            --retry 3 \
            --retry-delay 5 \
            --connect-timeout 30 \
            --max-time 60
        timeout-minutes: 3
