name: Enviar Palabra del Día

on:
  # Corre todos los días a las 15:00 UTC → 12:00 Córdoba/Argentina
  schedule:
    - cron: '0 15 * * *'

  # También lo podés ejecutar manualmente desde GitHub
  workflow_dispatch:

jobs:
  enviar-devocional:
    runs-on: ubuntu-latest
    steps:
      - name: Enviar notificación diaria
        run: |
          curl -X POST https://fundacionmisionvida7.vercel.app/api/send-notification \
            -H "Content-Type: application/json" \
            -d '{
              "title": "📖 Palabra del Día",
              "body":  "¡Tu devocional de hoy ya está disponible!"
            }'
