name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy Backend & Notify Update
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to Vercel
        run: npx vercel --prod --token ${{ secrets.VERCEL_TOKEN }} --yes

      - name: Send Update Notification via FCM
        run: |
          echo "🔔 Enviando notificación de actualización..."
          curl -X GET "https://nuevo-palabra-del-dia-backend.vercel.app/api/send-notification?type=update"
