jobs:
  deploy:
    # … tu job que hace build y deploy …
  notify_update:
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Avisar nueva versión
        run: |
          curl -X GET "https://nuevo-palabra-del-dia-backend.vercel.app/api/send-notification?type=updates" \
            -H "Content-Type: application/json"
