jobs:
  deploy:
    name: Deploy Backend & Notify Update
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: npm ci

      # Omite build si no tienes script en package.json

      - name: Deploy to Vercel
        run: npx vercel --prod --token ${{ secrets.VERCEL_TOKEN }} --yes

      - name: Send Update Notification via FCM
        run: |
          curl -X GET "https://nuevo-palabra-del-dia-backend.vercel.app/api/send-notification?type=update" \
            -H "Content-Type: application/json"
