name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy Backend & Notify Update
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm ci

      # Como no tienes "build", eliminamos este paso:
      # - name: Build project
      #   run: npm run build

      - name: Deploy to Vercel
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: npx vercel --prod --confirm

      - name: Send Update Notification via FCM
        # <-- este paso corre justo tras el deploy
        run: |
          curl -X GET "https://nuevo-palabra-del-dia-backend.vercel.app/api/send-notification?type=update" \
            -H "Content-Type: application/json"
