name: Verificar si hay Culto en Vivo

on:
  schedule:
    - cron: '*/15 17-23 * * *'  # Cada 15 minutos de 17:00 a 23:00 hora local
  workflow_dispatch:

jobs:
  check-live:
    runs-on: ubuntu-latest

    steps:
      - name: Debug: Listar nombres de env
        run: |
          env | grep -E 'FIREBASE_SERVICE_ACCOUNT|YOUTUBE_API_KEY|YOUTUBE_CHANNEL_ID|NOTIF_ENDPOINT'

      - name: Instalar herramientas
        run: |
          sudo apt-get update
          sudo apt-get install -y jq curl

      - name: Verificar transmisión en vivo y notificar
        env:
          FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
          YOUTUBE_API_KEY:        ${{ secrets.YOUTUBE_API_KEY }}
          YOUTUBE_CHANNEL_ID:     ${{ secrets.YOUTUBE_CHANNEL_ID }}
          NOTIF_ENDPOINT:         ${{ secrets.NOTIF_ENDPOINT }}
        run: |
          echo "🔍 Consultando YouTube Live..."
          RESPONSE=$(curl -s "https://www.googleapis.com/youtube/v3/search?part=snippet&channelId=$YOUTUBE_CHANNEL_ID&eventType=live&type=video&key=$YOUTUBE_API_KEY")
          LIVE_VIDEO_ID=$(echo "$RESPONSE" | jq -r '.items[0].id.videoId // empty')

          if [ -z "$LIVE_VIDEO_ID" ]; then
            echo "❌ No hay transmisión en vivo."
            exit 0
          fi
          echo "📺 Transmisión en vivo: $LIVE_VIDEO_ID"

          echo "$FIREBASE_SERVICE_ACCOUNT" > firebase-key.json
          gcloud auth activate-service-account --key-file=firebase-key.json

          LAST_ID=$(
            gcloud firestore documents describe \
              projects/$(gcloud config get-value project)/databases/(default)/documents/liveStatus/lastLive \
              --format="value(fields.liveVideoId.stringValue)"
          )

          if [ "$LIVE_VIDEO_ID" = "$LAST_ID" ]; then
            echo "⏸ Ya notificado: $LAST_ID"
            exit 0
          fi

          echo "✅ Video nuevo, enviando notificación..."
          curl -s "$NOTIF_ENDPOINT"

          echo "💾 Actualizando Firestore con el nuevo ID..."
          gcloud firestore documents update \
            projects/$(gcloud config get-value project)/databases/(default)/documents/liveStatus/lastLive \
            --update-field="liveVideoId=$LIVE_VIDEO_ID"

          echo "✔️ Listo."
